paths:
  /api/products: 
    get:
      summary: Obtiene todos los usuarios
      tags:
        - Products
      responses:
        "200":
          description: Los usuarios fueron obtenidos satisfactoriamente de la BDD
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o fallo en la conexión a la BDD
  /api/products/{uid}:
    get:
      summary: Obtiene un solo usuario a partir de su uid
      tags:
        - Products
      parameters:
        - name: uid
          in: path
          required: true
          description: El id del usuario
          schema:
            $type: String
      responses:
        "200":
          description: El usuario fue obttenido satisfcatoriamente de la BDD
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o fallo en la conexión a la BDD
    put:
      summary: Actualiza el usuario a partir de su uid
      tags:
        - Products
      parameters:
        - name: uid
          in: path
          required: true
          description: El id del usuario
          schema:
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateUser'
      responses:
        "200":
          description: El usuario fue actualizado correctamente
        "404":
          description: El usuario no fue encontrado en la BDD
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o fallo en la conexión a la BDD
components:
  schemas:
    Product:
      type: object
      required:
        - title
        - description
        - code
        - stock
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado de mongodb
        title:
          type: String
          description: Nombre del producto
          required: true
        description:
          type: String
          description: Descripción del producto
          required: true
        price:
          type: Number
          description: Precio de venta del producto
        code:
          type: Number
          description: Código del producto, el mismo es único y se encuentra indexado
          required: true
        stock:
          type: Numbrer
          description: Existencia del producto. Por defecto en 0
          required: true
        category:
          type: String
          description: Categoría del producto  
        thumbnail:
          type: Array
          description: Imágenes del producto, las mismas se almacen en link
        status:
          type: Boolean
          description: Estado del producto    
        owner:
          type: String
          description: Usuario creador del producto      
      example:
        _id: ObjectId("6462b9af05a9b3e33768045a")
        title: Anillo de Diamantes
        description: compralo hasta en 12 cuotas.
        price: 3500
        code: 101
        stock: 22
        category: Joyeria
        thumbnail: ["https://i.postimg.cc/zvSK4m47/Anillo1.png"]
        status: true
        owner: cdiblasi@bykom.com
  requestBodies:
    updateUser:
      type: object
      properties:
        first_name:
          type: String
          description: Nombre del usuario
        last_name:
          type: String
          description: Apellido del usuario
        email:
          type: String
          description: Correo del usuario
        password:
          type: String
          description: Password del usuario
        role:
          type: String
          description: Rol del usuario
      example:
        first_name: Jose
        last_name: Guerra
        email: hg@gmail.com
        password: $asd645
        role: admin